### ISSUE TITLE
Group click statistics by PR/issue ID

### ISSUE THREAD

**Issue by Agares** [bbaga/github-scheduled-reminder-app#44]
The current statistics only show how many clicks there were on a given type (i.e. pull request or issue), it'd be nice to see how many times a PR or issue was clicked.
Note: PR and issue ID are in the same namespace (i.e. there will never be a PR with the same ID as an issue)

**Comment by bbaga** [comment]
👋  @Agares does the proposed format in #56 match your expectation?

**Comment by Agares** [comment]
Looks great 🚀
